baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'satRday'
theme= 'satRday'

[params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "satRday [My City]"
    subtitle = "A conference for users of the R Language on [Conference Date]"
    bg = true
    buttonText = "Tell me more"