baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'satRday'
theme= 'satRday'

[params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "satRday [My City]"
    subtitle = "A conference for users of the R Language on [Conference Date]"
    bg = true
    buttonText = "Tell me more"

[params.services]
    enable = true
    title = "About"
    subtitle = "Conference Details"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-calendar-check"
      title = "Details"
      description = "[Conference Date] at [Conference Location]"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Hands on"
      description = "Practical applications and workshop sessions"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-graduation-cap"
      title = "Learning"
      description = "Gain knowledge from your peers and experienced professionals"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Community Lead"
      description = "Community organised, community focussed"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-money-bill"
      title = "Affordable"
      description = "Only [£30]"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-universal-access"
      title = "Accessible"
      description = "Inclusive, supportive and respectful environment"
      url = "#"